<?php

namespace JuniorEsiee\BusinessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.depositDate');
    }
}
