<?php

namespace JuniorEsiee\BusinessBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Sonata\UserBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.depositDate');
    }

    public function queryUsers(User $user)
    {
        return $this->createQueryBuilder('p')
        	->leftJoin('p.students', 'stu')
        	->where('p.commercial = :user')
        	->orWhere('p.rbu = :user')
        	->orWhere('stu.id = :user')
        		->setParameter('user', $user->getId())
            ->orderBy('p.depositDate');
    }

    public function queryWaitingCommercial()
    {
        return $this->createQueryBuilder('p')
        	->where('p.commercial is NULL')
            ->orderBy('p.depositDate');
    }

    public function queryWaitingStudents()
    {
        return $this->createQueryBuilder('p')
        	->leftJoin('p.students', 'stu')
        	->where('COUNT(stu.id) = 0')
            ->orderBy('p.depositDate');
    }

    public function queryMissingInfo()
    {
        return $this->createQueryBuilder('p')
        	->where('p.state = "state_waiting_information"')
            ->orderBy('p.depositDate');
    }
}
