<?php

namespace JuniorEsiee\FinancesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableRepository extends EntityRepository
{
	function findAllVars()
	{
		$vars          = $this->findAll();
		$varsFormatted = array();

		foreach ($vars as $var) {
			$varsFormatted[$var->getSlug()] = $var->getValue().' '.$var->getUnit();
		}

		return $varsFormatted;
	}
}
