<?php

namespace JuniorEsiee\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Sonata\UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function countUnreadNotifications(User $user)
    {
        return $this->createQueryBuilder('n')
        	->select('COUNT(n)')
        	->where('n.user = :user')
        		->setParameter('user', $user->getId())
        	->andWhere('n.notificationRead = 0')
 			->getQuery()
        	->getSingleScalarResult()
        ;
    }
}
