<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.firstname, u.lastname');
    }
}
