<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.firstname, u.lastname');
    }

    public function queryWithSkillCategory(\Doctrine\Common\Collections\Collection $skillCategories)
    {
    	$i = 0;
    	$q = $this->createQueryBuilder('u')
        	->leftJoin('u.skillCategories', 'sk')
            ;

        foreach ($skillCategories as $skillCategory) {
        	$q
	        	->orWhere('sk.id = :skillcategory'.$i)
	        		->setParameter('skillcategory'.$i, $skillCategory->getId())
	        ;
	        $i++;
        }

        return $q
        	->orderBy('u.firstname, u.lastname')
	        ->getQuery()
	        ->getResult();
    }
}
