<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.firstname, u.lastname');
    }

    public function findWithSkillCategory(\Doctrine\Common\Collections\Collection $skillCategories)
    {
    	$i = 0;
    	$q = $this->createQueryBuilder('u')
        	->leftJoin('u.skillCategories', 'sk')
        ;

        foreach ($skillCategories as $skillCategory) {
        	$q
	        	->orWhere('sk.id = :skillcategory'.$i)
	        		->setParameter('skillcategory'.$i, $skillCategory->getId())
	        ;
	        $i++;
        }

        return $q
        	->orderBy('u.firstname, u.lastname')
	        ->getQuery()
	        ->getResult()
        ;
    }

    public function findByRoles($roles) {
        $q = $this->createQueryBuilder('u')
            ->leftJoin('u.group', 'g');
        $i = 0;

        foreach ($roles as $role) {
            $q
                ->andWhere("u.roles LIKE :role$i OR g.roles LIKE :role$i")
                    ->setParameter("role$i", '%"'.$role.'"%')
            ;
            $i++;
        }

        return $q->getQuery()->getResult();
    }
}
